config/routes.rb
Europodatki::Application.routes.draw do
  resources :enclosures

  resources :agents

  resources :bills

  resources :clearings do
    member do
      get 'history'
    end
    resource :bill, only: [:new]
    resources :messages, only: [:new, :index]
    resources :enclosures, only: [:new, :index]
  end

  resources :companies

  resources :documents

  resources :countries do
    resources :documents, only: [:new, :index]
  end

  resources :messages

  resources :clients do
    member do
      get 'history'
    end
    collection do
      get 'autocomplete_client_lastname'
    end
    resources :clearings, only: [:new, :index]
  end

  devise_for :users
  resources :users, :only => [:show, :index]

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  root :to => 'home#index'

  match 'home/administration' => 'home#administration', :as => 'home_administration'
  match 'home/reports' => 'home#reports', :as => 'home_reports'
  match 'home/bills_report' => 'home#bills_report', :as => 'home_bills_report'
  match 'home/clearings_report' => 'home#clearings_report', :as => 'home_clearings_report'
  #match 'home/countries_report' => 'home#countries_report', :as => 'home_countries_report'
  match 'home/file_upload' => 'home#file_upload', :as => 'home_file_upload'
  match 'home/envelope' => 'home#envelope', :as => 'home_envelope'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :clearing
  attr_accessible :body, :origin, :source, :clearing_id, :user_id

  validates_presence_of :origin, :source, :clearing_id, :user_id, :body

  def self.all_cached
    Rails.cache.fetch('Message.all') { all }
  end

  after_save :expire_all_cache
  after_destroy :expire_all_cache

  def expire_all_cache
    Rails.cache.delete('Message.all')
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :authenticate_user!

  # GET /messages
  # GET /messages.json
  def index
    if params[:clearing_id]
      clearing = Clearing.find params[:clearing_id]
      @messages = clearing.messages
    else
      @messages = Message.all_cached
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    if params[:clearing_id]
      @clearing = Clearing.find(params[:clearing_id])
      @message = @clearing.messages.build
    else
      @message = Message.new
    end

    if params[:client_id]
      client = Client.find(params[:client_id])
      @clearings = client.clearings
    else
      @clearings = Clearing.all_cached
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
    @clearings = @message.clearing.client.clearings
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(check_number_with_comma(params[:message]))
    @message.user_id = current_user.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: t('flash.notice') }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(check_number_with_comma(params[:message]))
        format.html { redirect_to @message, notice: t('flash.notice') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: t('flash.notice') if @message.destroyed? }
      format.json { head :no_content }
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
    <% if @message.errors.any? %>
        <div id="error_explanation">
          <h2><%= "Wykrytych błędów: #{@message.errors.count}" %></h2>

          <ul>
            <% @message.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="table">
      <table class="listing form" cellpadding="0" cellspacing="0">
        <tr>
          <th class="full" colspan="2">Formularz nowej wiadomości</th>
        </tr>
        <tr>
          <td><strong><%= f.label :source, 'Źródło' %></strong></td>
          <td> <%= f.select :source, options_for_select(['Telefon', 'Wiadomość e-mail', 'Spotkanie', 'List tradycyjny', 'Inne'], @message.source), {prompt: true} %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :origin, 'Pochodzenie' %></strong></td>
          <td> <%= f.select :origin, options_for_select(%w(Przychodząca Wychodząca Inna), @message.origin), {prompt: true} %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :body, 'Treść' %></strong></td>
          <td> <%= f.text_area :body %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :clearing_id, "Rozliczenie powiązane z tą wiadomością" %></strong></td>
          <td>
            <% if @clearings %>
            <%= f.collection_select :clearing_id, @clearings, :id, :title, {prompt: true} %>
                <% else %>
                <%= f.collection_select :clearing_id, Clearing.all_cached, :id, :title, {prompt: true} %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td class="full" colspan="2"><%= f.submit "Zapisz" %></td>
        </tr>
      </table>
    </div>
<% end %>

app/views/messages/_main_menu.html.erb
<% if @message && !@message.new_record? %>
    <h3><%= "Wiadomość" %></h3>
    <ul class="nav">
      <li><%= link_to 'Szczegóły', @message %></li>
      <li><%= link_to 'Edycja', edit_message_path(@message) %></li>
      <li><%= link_to 'Usuń', @message, :confirm => "Czy jesteś pewien?", :method => :delete %></li>
      <li><%= link_to 'Do klienta', @message.clearing.client %></li>
      <li><%= link_to 'Do rozliczenia', @message.clearing %></li>
    </ul>
<% end %>
<h3>Wiadomości</h3>
<ul class="nav">
  <li><%= link_to 'Nowa wiadomość', new_message_path %></li>
  <li><%= link_to 'Lista wiadomości', messages_path %></li>
  <li></li>
</ul>

app/views/messages/_message.html.erb
<%= content_tag :td, (link_to message.source, message_path(message)), class: 'style1' %>
<%= content_tag :td, (link_to message.origin, message_path(message)), class: 'style1' %>
<%= content_tag :td, check_blank_value(truncate(message.body, length: 25)) %>
<%= content_tag :td, check_blank_value(message.user.name) %>
<%= content_tag :td, check_blank_value(message.created_at) %>
<%= content_tag :td, (link_to message.clearing.title, client_path(message.clearing)), class: 'style1' %>
<%= content_tag :td, (link_to message.clearing.client.lastname, client_path(message.clearing.client)), class: 'style1' %>
<%= content_tag :td, class: 'actions' do %>
    <%= link_to image_tag('info.png'), message, title: "Szczegółowe informacje" %>
    <%= link_to image_tag('modify.png'), edit_message_path(message), title: "Edycja" %>
    <%= link_to image_tag('delete.png'), message, :confirm => "Czy jesteś pewien?", :method => :delete, title: "Usuwanie" %>
<% end %>

app/views/messages/_messages_table.html.erb
<%= content_tag :div, class: 'table' do %>
    <table class="listing jquery_datatable" cellpadding="0" cellspacing="0">
      <thead>
      <%= content_tag :tr do %>
          <%= content_tag :th, 'Źródło' %>
          <%= content_tag :th, 'Pochodzenie' %>
          <%= content_tag :th, 'Treść' %>
          <%= content_tag :th, 'Użytkownik' %>
          <%= content_tag :th, 'Data utworzenia' %>
          <%= content_tag :th, 'Rozliczenie' %>
          <%= content_tag :th, 'Klient' %>
          <%= content_tag :th, 'Akcje' %>
      <% end %>
      </thead>
      <tbody>
      <%= content_tag_for(:tr, messages) do |message| %>
          <%= render message %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/messages/edit.html.erb
<% content_for :section_header do %>
    Edycja wiadomości
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Edycja wiadomości", edit_message_path(@message) %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Edycja już utworzonej wiadomości' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<%= render 'form' %>

app/views/messages/index.html.erb
<% content_for :section_header do %>
    Lista wiadomości
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Lista wiadomości", messages_path %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Lista wszystkich wiadomości utworzonych w systemie dla klientów' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<%= content_tag :div, class: 'table' do %>
    <table class="listing jquery_datatable" cellpadding="0" cellspacing="0">
      <thead>
      <%= content_tag :tr do %>
          <%= content_tag :th, 'Źródło' %>
          <%= content_tag :th, 'Pochodzenie' %>
          <%= content_tag :th, 'Treść' %>
          <%= content_tag :th, 'Użytkownik' %>
          <%= content_tag :th, 'Data utworzenia' %>
          <%= content_tag :th, 'Rozliczenie' %>
          <%= content_tag :th, 'Klient' %>
          <%= content_tag :th, 'Akcje' %>
      <% end %>
      </thead>
      <tbody>
      <%= content_tag_for(:tr, @messages) do |message| %>
         <%= render message %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/messages/new.html.erb
<% content_for :section_header do %>
    Dodawanie nowej wiadomości
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Dodawanie wiadomości", new_message_path %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Dodawanie nowej wiadomości' %>
    <% help_block 'Data utworzenia wiadomości dopiszę się automatycznie w momencie kliknięcia przycisku Zapisz' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<%= render 'form' %>

app/views/messages/show.html.erb
<% content_for :section_header do %>
    Szczegóły wiadomości
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Szczegóły wiadomości", message_path(@message) %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Podgląd danych wiadomości' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<div class="table">
  <table class="listing form" cellpadding="0" cellspacing="0">
    <tr>
      <th class="full" colspan="2">Szczegóły rekordu wiadomości</th>
    </tr>
    <tr>
      <td>Rozliczenie</td>
      <td><strong><%= link_to @message.clearing.title, clearing_path(@message.clearing) %></strong></td>
    </tr>
    <tr>
      <td>Klient</td>
      <td><strong><%= link_to @message.clearing.client.lastname, client_path(@message.clearing.client) %></strong></td>
    </tr>
    <%= check_blank 'Źródło', @message.source %>
    <%= check_blank 'Pochodzenie', @message.origin %>
    <tr>
      <td>Data utworzenia</td>
      <td><strong><%= check_blank_value @message.created_at %></strong></td>
    </tr>
    <tr>
      <td>Użytkownik</td>
      <td><strong><%= link_to @message.user.name, user_path(@message.user) %></strong></td>
    </tr>
    <tr>
      <th class="full" colspan="2">Treść wiadomości</th>
    </tr>
    <tr>
      <td colspan="2"><%= @message.body.blank? ? "Brak" : @message.body %></td>
    </tr>
  </table>
</div>