config/routes.rb
Europodatki::Application.routes.draw do
  resources :enclosures

  resources :agents

  resources :bills

  resources :clearings do
    member do
      get 'history'
    end
    resource :bill, only: [:new]
    resources :messages, only: [:new, :index]
    resources :enclosures, only: [:new, :index]
  end

  resources :companies

  resources :documents

  resources :countries do
    resources :documents, only: [:new, :index]
  end

  resources :messages

  resources :clients do
    member do
      get 'history'
    end
    collection do
      get 'autocomplete_client_lastname'
    end
    resources :clearings, only: [:new, :index]
  end

  devise_for :users
  resources :users, :only => [:show, :index]

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  root :to => 'home#index'

  match 'home/administration' => 'home#administration', :as => 'home_administration'
  match 'home/reports' => 'home#reports', :as => 'home_reports'
  match 'home/bills_report' => 'home#bills_report', :as => 'home_bills_report'
  match 'home/clearings_report' => 'home#clearings_report', :as => 'home_clearings_report'
  #match 'home/countries_report' => 'home#countries_report', :as => 'home_countries_report'
  match 'home/file_upload' => 'home#file_upload', :as => 'home_file_upload'
  match 'home/envelope' => 'home#envelope', :as => 'home_envelope'
end

app/models/client.rb
#encoding: utf-8
class Client < ActiveRecord::Base
  audited protect: false #, comment_required: true

  has_one :address, dependent: :destroy, conditions: ['kind = ?', 'address']
  has_one :mailing_address, class_name: 'Address', dependent: :destroy, conditions: ['kind = ?', 'mailing_address']
  belongs_to :user
  has_many :messages, through: :clearings
  has_many :clearings, dependent: :destroy
  has_many :bills, through: :clearings
  has_many :enclosures, through: :clearings

  attr_accessible :birthdate, :description, :email, :firstname, :lastname, :middlename, :mobile, :telephone, :user_id, :address_attributes, :mailing_address_attributes, :children_data, :married, :married_date, :married_data

  accepts_nested_attributes_for :address, :allow_destroy => true
  accepts_nested_attributes_for :mailing_address, :allow_destroy => true

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :identifier, presence: true
  validates_numericality_of :identifier
  validates_uniqueness_of :identifier

  before_validation :check_addresses
  before_validation :set_identifier

  def self.all_cached
    Rails.cache.fetch('Client.all') { Client.includes([:address, :mailing_address]).order("lastname") }
  end

  after_save :expire_all_cache
  after_destroy :expire_all_cache

  def expire_all_cache
    Rails.cache.delete('Client.all')
  end

  def get_married_description
    case self.married
      when 0
        return "Panna/Kawaler"
      when 1
        return "Mężatka/Żonaty"
      when 2
        return "Rozwiedziona/Rozwiedziony"
      when 3
        return "Wdowa/Wdowiec"
      else
        return "Nie rozpoznano wartości"
    end
  end

  def fullname
    self.lastname + ' ' + self.firstname
  end

  private
  def check_addresses
    if self.mailing_address.city.blank? && !self.address.city.blank?
      self.mailing_address.city = self.address.city
    end
    if self.mailing_address.street.blank? && !self.address.street.blank?
      self.mailing_address.street = self.address.street
    end
    if self.mailing_address.code.blank? && !self.address.code.blank?
      self.mailing_address.code = self.address.code
    end
  end

  def set_identifier
    self.identifier = (Client.maximum(:identifier) || 9999) + 1 if self.identifier.nil?
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_filter :authenticate_user!

  autocomplete :client, :lastname, :extra_data => [:firstname], :display_value => :fullname

  # GET /clients
  # GET /clients.json
  def index
    #@clients = Client.all_cached

    if params[:client]
      @search = Client.search :lastname_cont => lastname_parser(params[:client][:lastname])
      @clients = @search.result
      params.clear
    else
      @clients = Client.all_cached
    end

    redirect_to @clients.first and return if (@clients.size.eql?(1))

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new
    @client.address = Address.new
    @client.mailing_address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/history
  def history
    @client = Client.find(params[:id])
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(check_number_with_comma(params[:client]))
    @client.user_id = current_user.id

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: t('flash.notice') }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(check_number_with_comma(params[:client]))
        format.html { redirect_to @client, notice: t('flash.notice') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: t('flash.notice') if @client.destroyed? }
      format.json { head :no_content }
    end
  end

  private
  def lastname_parser(fullname)
    fullname.split.first
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
    <% if @client.errors.any? %>
        <div id="error_explanation">
          <h2><%= "Wykrytych błędów: #{@client.errors.count}" %></h2>

          <ul>
            <% @client.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="table">
      <table class="listing form" cellpadding="0" cellspacing="0">
        <tr>
          <th class="full" colspan="2">Formularz klienta</th>
        </tr>
        <tr>
          <td><strong><%= f.label :lastname, 'Nazwisko' %></strong></td>
          <td> <%= f.text_field :lastname %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :firstname, 'Imię' %></strong></td>
          <td> <%= f.text_field :firstname %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :middlename, 'Drugie imię' %></strong></td>
          <td> <%= f.text_field :middlename %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :birthdate, 'Data urodzenia' %></strong></td>
          <td> <%= f.datepicker :birthdate, class: 'datepicker' %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :telephone, 'Telefon stacjonarny' %></strong></td>
          <td> <%= f.text_field :telephone %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :mobile, 'Telefon komórkowy' %></strong></td>
          <td><%= f.text_field :mobile %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :email, 'E-mail' %></strong></td>
          <td><%= f.email_field :email %></td>
        </tr>
        <tr>
          <th class="full" colspan="2">Adres zameldowania</th>
        </tr>

        <%= f.fields_for :address do |address_form| %>
            <tr>
              <td><strong><%= address_form.label :street, "Ulica, nr domu/mieszkania" %></strong></td>
              <td><%= address_form.text_field :street %></td>
            </tr>
            <tr>
              <td><strong><%= address_form.label :city, "Miasto" %></strong></td>
              <td><%= address_form.text_field :city %></td>
            </tr>
            <tr>
              <td><strong><%= address_form.label :code, "Kod pocztowy" %></strong></td>
              <td><%= address_form.text_field :code %></td>
            </tr>
            <%= address_form.hidden_field :kind, value: 'address' %>
            <!--
            <% unless address_form.object.new_record? %>
                <tr>
                  <td><strong><%= address_form.label :_destroy, 'Usuń' %></strong></td>
                  <td><%= address_form.check_box :_destroy %></td>
                </tr>
            <% end %>
            -->
        <% end %>
        <tr>
          <th class="full" colspan="2">Adres korespondencyjny</th>
        </tr>
        <%= f.fields_for :mailing_address do |mailing_address_form| %>
            <tr>
              <td><strong><%= mailing_address_form.label :street, "Ulica, nr domu/mieszkania" %></strong></td>
              <td><%= mailing_address_form.text_field :street %></td>
            </tr>
            <tr>
              <td><strong><%= mailing_address_form.label :city, "Miasto" %></strong></td>
              <td><%= mailing_address_form.text_field :city %></td>
            </tr>
            <tr>
              <td><strong><%= mailing_address_form.label :code, "Kod pocztowy" %></strong></td>
              <td><%= mailing_address_form.text_field :code %></td>
            </tr>
            <%= mailing_address_form.hidden_field :kind, value: 'mailing_address' %>
            <!--
            <% unless mailing_address_form.object.new_record? %>
                <tr>
                  <td><strong><%= mailing_address_form.label :_destroy, 'Usuń' %></strong></td>
                  <td><%= mailing_address_form.check_box :_destroy %></td>
                </tr>
            <% end %>
            -->
        <% end %>
        <tr>
          <th class="full" colspan="2">Stan cywilny / rodzina</th>
        </tr>
        <tr>
          <td><strong><%= f.label :married, 'Stan cywilny' %></strong></td>
          <td> <%= f.select :married, options_for_select([['Panna/Kawaler', 0], ['Mężatka/Żonaty', 1], ['Rozwiedziona/Rozwiedziony', 2], ['Wdowa/Wdowiec', 3]], @client.married) %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :married_date, 'Data ślubu/rozwodu' %></strong></td>
          <td><%= f.datepicker :married_date, class: 'datepicker' %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :married_data, 'Informacje o żonie/mężu' %></strong></td>
          <td><%= f.text_area :married_data, :rows => 2 %></td>
        </tr>
        <tr>
          <td><strong><%= f.label :children_data, 'Informacje o dzieciach' %></strong></td>
          <td><%= f.text_area :children_data, :rows => 2 %></td>
        </tr>
        <tr>
          <th class="full" colspan="2">Inne informacje</th>
        </tr>
        <tr>
          <td><strong><%= f.label :description, 'Opis / uwagi' %></strong></td>
          <td><%= f.text_area :description, :rows => 2 %></td>
        </tr>
        <tr>
          <td class="full" colspan="2"><%= f.submit "Zapisz" %></td>
        </tr>
      </table>
    </div>
<% end %>

app/views/clients/_main_menu.html.erb
<% if @client && !@client.new_record? %>
    <h3><%= @client.lastname %></h3>
    <ul class="nav">
      <li><%= link_to 'Nowe rozliczenie', new_client_clearing_path(@client) %></li>
      <li><%= link_to 'Nowa wiadomość', new_message_path(:client_id => @client) %></li>
      <li><%= link_to 'Rozliczenia', client_clearings_path(@client) %></li>
      <li><%= link_to 'Szczegóły', @client %></li>
      <li><%= link_to 'Edycja', edit_client_path(@client) %></li>
      <li><%= link_to 'Historia', history_client_path(@client) %></li>
      <li><%= link_to 'Koperta', home_envelope_path(:search => {:client_id => @client.id}) %></li>
      <li><%= link_to 'Usuń', @client, :confirm => "Czy jesteś pewien?", :method => :delete %></li>
      <li></li>
    </ul>
<% end %>
<h3>Klienci</h3>
<ul class="nav">
  <li><%= link_to 'Nowy klient', new_client_path %></li>
  <li><%= link_to 'Lista klientów', clients_path %></li>
  <li></li>
</ul>

app/views/clients/edit.html.erb
<% content_for :section_header do %>
    Edycja klienta
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Edycja klienta", edit_client_path(@client) %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'W tym miejscu aplikacji możliwa jest edycja danych klienta.' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<%= render 'form' %>

app/views/clients/history.erb
<% content_for :section_header do %>
    Historia zmian klienta
<% end %>

<% content_for :history do %>
    <%= link_to "Strona główna", root_url %> / <%= link_to "Szczegóły klienta", client_path(@client) %> / <%= link_to "Historia klienta", history_client_path(@client) %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Podgląd danych historycznych klienta' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<p>
  Ilość wpisów w historii klienta: <%= @client.audits.size %>
</p>
<% @client.audits.reverse.each do |audit| %>
    <div class="table">
      <table class="listing form" cellpadding="0" cellspacing="0">
        <tr>
          <th class="full" colspan="2">Wersja <%= audit.version %></th>
        </tr>
        <tr>
          <td>Akcja</td>
          <td><strong><%= audit.action %></strong></td>
        </tr>
        <tr>
          <td>Zmiany</td>
          <td><strong><%= audit.audited_changes %></strong></td>
        </tr>
        <tr>
          <td>Komentarz</td>
          <td><strong><%= audit.comment %></strong></td>
        </tr>
        <tr>
          <td>Autor</td>
          <td><strong><%= audit.user.name %></strong></td>
        </tr>
        <tr>
          <td>Data</td>
          <td><strong><%= audit.created_at %></strong></td>
        </tr>
      </table>
    </div>
    <%# audit.revision.inspect %><%# zwraca instancję obiektu zmienione w chwili zmiany %>
<% end %>

app/views/clients/history.html.erb
<% content_for :section_header do %>
    Historia zmian klienta
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Szczegóły klienta", client_path(@client) %> / <%= link_to "Historia klienta", history_client_path(@client) %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Podgląd danych historycznych klienta' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<p>
  Ilość wpisów w historii klienta: <%= @client.audits.size %>
</p>
<% @client.audits.reverse.each do |audit| %>
    <div class="table">
      <table class="listing form" cellpadding="0" cellspacing="0">
        <tr>
          <th class="full" colspan="2">Wersja <%= audit.version %></th>
        </tr>
        <tr>
          <td>Akcja</td>
          <td><strong><%= audit.action %></strong></td>
        </tr>
        <tr>
          <td>Zmiany</td>
          <td><strong><%= audit.audited_changes %></strong></td>
        </tr>
        <tr>
          <td>Komentarz</td>
          <td><strong><%= audit.comment %></strong></td>
        </tr>
        <tr>
          <td>Autor</td>
          <td><strong><%= audit.user.name %></strong></td>
        </tr>
        <tr>
          <td>Data</td>
          <td><strong><%= audit.created_at %></strong></td>
        </tr>
      </table>
    </div>
    <%# audit.revision.inspect %><%# zwraca instancję obiektu zmienione w chwili zmiany %>
<% end %>

app/views/clients/index.html.erb
<% content_for :section_header do %>
    Lista klientów
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Lista klientów", clients_path %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Lista wszystkich rekordów z bazy danych' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<%= content_tag :div, class: 'table' do %>
    <table class="listing jquery_datatable" cellpadding="0" cellspacing="0">
      <thead>
      <%= content_tag :tr do %>
          <%= content_tag :th, 'Nazwisko' %>
          <%= content_tag :th, 'Imię' %>
          <%= content_tag :th, 'Identyfikator' %>
          <%= content_tag :th, 'Miasto' %>
          <%= content_tag :th, 'Telefon kom' %>
          <%= content_tag :th, 'E-mail' %>
          <%= content_tag :th, 'Akcje' %>
      <% end %>
      </thead>
      <tbody>
      <%= content_tag_for(:tr, @clients) do |client| %>
          <%= content_tag :td, (link_to client.lastname, client_path(client)), class: 'style1' %>
          <%= content_tag :td, (link_to client.firstname, client_path(client)), class: 'style1' %>
          <%= content_tag :td, (link_to client.identifier, client_path(client)), class: 'style1' %>
          <%= content_tag :td, check_blank_value(client.address.city) %>
          <%= content_tag :td, check_blank_value(client.mobile) %>
          <% if client.email %>
            <%= content_tag :td, (link_to client.email, "mailto:#{client.email}") %>
          <% else %>
            <%= content_tag :td, (link_to check_blank_value(client.email)) %>
          <% end %>
          <%= content_tag :td, class: 'actions' do %>
              <%= link_to image_tag('info.png'), client, title: "Szczegółowe informacje" %>
              <%= link_to image_tag('modify.png'), edit_client_path(client), title: "Edycja" %>
              <%= link_to image_tag('delete.png'), client, :confirm => "Czy jesteś pewien?", :method => :delete, title: "Usuwanie" %>
          <% end %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/clients/new.html.erb
<% content_for :section_header do %>
    Dodawanie nowego klienta
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Dodawanie klienta", new_client_path %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Dodawanie nowego rekordu klienta' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<%= render 'form' %>

app/views/clients/show.html.erb
<% content_for :section_header do %>
    Szczegóły klienta
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Szczegóły klienta", client_path(@client) %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Podgląd danych klienta' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<div class="table">
  <table class="listing form" cellpadding="0" cellspacing="0">
    <tr>
      <th class="full" colspan="2">Szczegóły rekordu klienta</th>
    </tr>
    <%= check_blank 'Identyfikator', @client.identifier %>
    <%= check_blank 'Nazwisko', @client.lastname %>
    <%= check_blank 'Imię', @client.firstname %>
    <%= check_blank 'Drugie imię', @client.middlename %>
    <%= check_blank 'Telefon stacjonarny', @client.telephone %>
    <%= check_blank 'Telefon komórkowy', @client.mobile %>
    <% if @client.email %>
      <%= check_blank 'E-mail', link_to(@client.email, "mailto:#{@client.email}") %>
    <% else %>
      <%= check_blank 'E-mail', @client.email %>
    <% end %>

    <tr>
      <td>Data urodzenia</td>
      <td><strong>
        <% if @client.birthdate.blank? %>
            Brak
        <% else %>
            <%= l @client.birthdate %>
        <% end %>
      </strong></td>
    </tr>
    <tr>
      <th class="full" colspan="2">Adres zameldowania</th>
    </tr>
    <%= check_blank 'Miasto', @client.address.city %>
    <%= check_blank 'Ulica nr domu/mieszkania', @client.address.street %>
    <%= check_blank 'Kod pocztowy', @client.address.code %>
    <tr>
      <th class="full" colspan="2">Adres korespondencyjny</th>
    </tr>
    <%= check_blank 'Miasto', @client.mailing_address.city %>
    <%= check_blank 'Ulica nr domu/mieszkania', @client.mailing_address.street %>
    <%= check_blank 'Kod pocztowy', @client.mailing_address.code %>
    <tr>
      <th class="full" colspan="2">Stan cywilny / rodzina</th>
    </tr>
    <%= check_blank 'Stan cywilny', @client.get_married_description %>
    <%= check_blank('Data ślubu/rozwodu', check_blank_value(@client.married_date)) %>
    <%= check_blank('Informacje o żonie/mężu', @client.married_data) %>
    <%= check_blank('Informacje o dzieciach', @client.children_data) %>
    <tr>
      <th class="full" colspan="2">Opis / uwagi</th>
    </tr>
    <tr>
      <td colspan="2"><%= @client.description.blank? ? "Brak" : @client.description %></td>
    </tr>
    <tr>
      <th class="full" colspan="2">Inne informacje</th>
    </tr>
    <tr>
      <%= check_blank 'Użytkownik tworzący', @client.user.try(:name) %>
    </tr>
  </table>
</div>

<h3>Rozliczenia klienta</h3>
<%= render partial: 'clearings/clearings_table', locals: {clearings: @client.clearings} %>

<h3>Rachunki klienta</h3>
<%= render partial: 'bills/bills_table', locals: {bills: @client.bills} %>

<h3>Wiadomości klienta(zbiorcze z rozliczeń)</h3>
<%= render partial: 'messages/messages_table', locals: {messages: @client.messages} %>

<h3>Załączniki klienta(zbiorcze z rozliczeń)</h3>
<%= render partial: 'enclosures/enclosures_table', locals: {enclosures: @client.enclosures} %>