config/routes.rb
Europodatki::Application.routes.draw do
  resources :enclosures

  resources :agents

  resources :bills

  resources :clearings do
    member do
      get 'history'
    end
    resource :bill, only: [:new]
    resources :messages, only: [:new, :index]
    resources :enclosures, only: [:new, :index]
  end

  resources :companies

  resources :documents

  resources :countries do
    resources :documents, only: [:new, :index]
  end

  resources :messages

  resources :clients do
    member do
      get 'history'
    end
    collection do
      get 'autocomplete_client_lastname'
    end
    resources :clearings, only: [:new, :index]
  end

  devise_for :users
  resources :users, :only => [:show, :index]

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  root :to => 'home#index'

  match 'home/administration' => 'home#administration', :as => 'home_administration'
  match 'home/reports' => 'home#reports', :as => 'home_reports'
  match 'home/bills_report' => 'home#bills_report', :as => 'home_bills_report'
  match 'home/clearings_report' => 'home#clearings_report', :as => 'home_clearings_report'
  #match 'home/countries_report' => 'home#countries_report', :as => 'home_countries_report'
  match 'home/file_upload' => 'home#file_upload', :as => 'home_file_upload'
  match 'home/envelope' => 'home#envelope', :as => 'home_envelope'
end

app/controllers/home_controller.rb
#encoding: utf-8

class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @clearings = Clearing.undone
  end

  def administration
    @countries = Country.all_cached
    @companies = Company.all_cached
    @documents = Document.all_cached
    @agents = Agent.all_cached
  end

  def envelope
    if params[:search]
      if params[:search][:client_id]
        @client = Client.find params[:search][:client_id]
      end
      if params[:search][:company_id]
        @company = Company.find params[:search][:company_id]
      end

      if @client && @company
        send_file Report.create_envelope(@client, @company), :filename => "koperta.pdf", :type => "application/pdf"
        return
      end
    end
  end

  def reports
  end

  def bills_report
    @no_html = false
    if params[:q]
      params[:q].deep_merge!("s" => "number asc")
    else
      params[:q] = {"s" => "number asc"}
      @no_html = true
    end
    @search = Bill.search(params[:q])
    @bills = @search.result(distinct: true)

    if params[:commit]
      if params[:commit].include? 'pdf'
        send_file Report.bills_report_to_pdf(@bills), :filename => "raport.pdf", :type => "application/pdf"
        return
      end

      if params[:commit].include? 'csv'
        send_file Report.bills_report_to_csv(@bills), :filename => "raport.csv", :type => "text/plain"
        return
      end
    end

    respond_to do |format|
      format.html
    end
  end

  def clearings_report
    @no_html = false
    unless params[:q]
      @no_html = true
    end

    @search = Clearing.search(params[:q])
    @clearings = @search.result(distinct: true)

    if params[:commit]
      if params[:commit].include? 'pdf'
        send_file Report.clearings_report_to_pdf(@clearings), :filename => "raport.pdf", :type => "application/pdf"
        return
      end

      if params[:commit].include? 'csv'
        send_file Report.clearings_report_to_csv(@clearings), :filename => "raport.csv", :type => "text/plain"
        return
      end
    end

    respond_to do |format|
      format.html
    end
  end

  #def countries_report
  #  @no_html = false
  #  unless params[:q]
  #    @no_html = true
  #  end
  #
  #  @search = Clearing.search(params[:q])
  #  @clearings = @search.result(distinct: true)
  #
  #  if params[:commit]
  #    if params[:commit].include? 'pdf'
  #      send_file Report.countries_report_to_pdf(@clearings), :filename => "raport.pdf", :type => "application/pdf"
  #      return
  #    end
  #
  #    if params[:commit].include? 'csv'
  #      send_file Report.countries_report_to_csv(@clearings), :filename => "raport.csv", :type => "text/plain"
  #      return
  #    end
  #  end
  #
  #  respond_to do |format|
  #    format.html
  #  end
  #end

  def file_upload
    file = params[:file_upload][:my_file].tempfile
    @tab = Array.new
    @clients = Array.new
    @clearings = Array.new
    @bills = Array.new
    @bills_rep = Array.new
    @clients_rep = Array.new
    @clearings_rep = Array.new
    @errors = Array.new
    File.open(file, 'r') do |f|
      f.readlines.each_with_index do |line, index|
        if index > 0
          cells_tab = line.chomp.split(';')
          if cells_tab.size == 32
            @tab << cells_tab
            logger.debug "Aktualna linia: #{cells_tab}"
            client = check_client cells_tab
            if client.nil?
              client = create_client cells_tab
              @clients << client unless client.nil?
            else
              @clients_rep << client
            end

            clearing = check_clearing cells_tab
            unless clearing.nil?
              @clearings_rep << clearing
            end
            if clearing.nil? && !client.nil?
              clearing = create_clearing(cells_tab, client) unless client.nil?
              @clearings << clearing unless clearing.nil?
            end

            unless cells_tab[25].empty?
              bill = check_bill cells_tab
              unless bill.nil?
                @bills_rep << bill
              end
              if bill.nil? && !clearing.nil? && !client.nil?
                bill = create_bill(cells_tab, clearing) unless clearing.nil?
                @bills << bill unless bill.nil?
              end

              @errors << cells_tab if bill.nil? || client.nil? || clearing.nil?
            else
              @errors << cells_tab if client.nil? || clearing.nil?
            end
          else
            @errors << cells_tab
          end
        end
      end
    end
  end

  private
  def check_client(cells_tab)
    Client.where("lastname=? AND firstname=? AND birthdate=?", cells_tab[0], cells_tab[1], prepare_date(cells_tab[5], '19')).first
  end

  def create_client(cells_tab)
    client = Client.new
    client.address = Address.new
    client.mailing_address = Address.new
    client.mailing_address.kind = 'mailing_address'
    client.address.street = cells_tab[2] unless cells_tab[2].empty?
    client.address.city = cells_tab[4] unless cells_tab[4].empty?
    client.address.code = cells_tab[3] unless cells_tab[3].empty?
    client.address.kind = 'address'
    client.lastname = cells_tab[0] unless cells_tab[0].empty?
    client.firstname = cells_tab[1] unless cells_tab[1].empty?
    client.birthdate = prepare_date(cells_tab[5], '19') unless cells_tab[5].empty?
    client.telephone = cells_tab[6] unless cells_tab[6].empty?
    client.mobile = cells_tab[7] unless cells_tab[7].empty?
    client.email = cells_tab[8] unless cells_tab[8].empty?
    client.user_id = current_user.id

    client.save ? client : nil
  end

  def check_clearing(cells_tab)
    Clearing.where('tax_number=? AND year=? AND rebate_final=?', cells_tab[9], cells_tab[10], cells_tab[20]).first
  end

  def create_clearing(cells_tab, client)
    clearing = Clearing.new
    clearing.tax_number = cells_tab[9] unless cells_tab[9].empty?
    clearing.year = cells_tab[10] unless cells_tab[10].empty?
    clearing.application_date = prepare_date(cells_tab[11]) unless cells_tab[11].empty? #data
    clearing.commission_percent = cells_tab[12].split(',').join('.') unless cells_tab[12].empty? #liczba
    clearing.commission_min = cells_tab[13].split(',').join('.') unless cells_tab[13].empty? #liczba
    clearing.commission_currency = cells_tab[14] unless cells_tab[14].empty?
    clearing.rebate_calc = cells_tab[16].split(',').join('.') unless cells_tab[16].empty? #liczba
    clearing.office_send_date = prepare_date(cells_tab[17]) unless cells_tab[17].empty? #data
    clearing.decision_date = prepare_date(cells_tab[19]) unless cells_tab[19].empty? #data
    clearing.rebate_final = cells_tab[20].split(',').join('.') unless cells_tab[20].empty? #liczba
    clearing.exchange_rate = cells_tab[21].split(',').join('.') unless cells_tab[21].empty? #liczba
    clearing.commission_date = prepare_date(cells_tab[22]) unless cells_tab[22].empty? #data
    clearing.commission_final = cells_tab[23].split(',').join('.') unless cells_tab[23].empty? #liczba
    clearing.payment_date = prepare_date(cells_tab[26]) unless cells_tab[26].empty? #data
    clearing.income_total = cells_tab[27].split(',').join('.') unless cells_tab[27].empty? #liczba  WPŁYW NA KONTO WBK kolumna AB!!!
    clearing.total_to_client = cells_tab[28].split(',').join('.') unless cells_tab[28].empty? #liczba
    clearing.income_exchange_rate = cells_tab[29].split(',').join('.') unless cells_tab[29].empty? #liczba
    clearing.agent_date = prepare_date(cells_tab[30]) unless cells_tab[30].empty? #data
    agent = Agent.where(name: cells_tab[31]).first
    if agent
      clearing.agent_id = agent.id
    else
      clearing.agent_id = Agent.where(name: 'INNY').first.id
    end

    unless cells_tab[27].empty? #columna AB
      clearing.bill_amount = cells_tab[23].split(',').join('.') unless cells_tab[23].empty? #liczba
      clearing.to_client_date = prepare_date(cells_tab[26]) unless cells_tab[26].empty? #data
      clearing.bank_account_destination = 'Zwrot podatku na konto firmy'
    end

    clearing.client_id = client.id
    clearing.user_id = current_user.id
    country = Country.where(short: cells_tab[15]).first
    clearing.country_id = country.id
    clearing.archive = true

    clearing.save ? clearing : nil
  end

  def check_bill(cells_tab)
    if cells_tab[25][0].eql?('K')
      company = Company.where(short: 'EP JAKUB').first
    else
      company = Company.where(short: 'EP GRAŻYNA').first
    end

    str = String.new cells_tab[25][1..-1]
    Bill.where('number=? AND company_id=?', str, company.id).first
  end

  def create_bill(cells_tab, clearing)
    if cells_tab[25][0].eql?('K')
      company = Company.where(short: 'EP JAKUB').first
    else
      company = Company.where(short: 'EP GRAŻYNA').first
    end

    bill = Bill.new
    bill.issue_date = prepare_date(cells_tab[22]) unless cells_tab[22].empty? #data
    bill.total = cells_tab[23].split(',').join('.') unless cells_tab[23].empty? #liczba
    bill.maturity_date = prepare_date(cells_tab[24]) unless cells_tab[24].empty? #data
    if cells_tab[25][0].eql?('K')
      bill.number = cells_tab[25][1..-1]
    else
      bill.number = cells_tab[25]
    end
    if cells_tab[27].empty? #columna AB
      bill.title = 'Usługa biurowa'
      bill.payment_form = 'Przelew'
    else
      bill.title = 'Usługa inkasa'
      bill.payment_form = 'Pobranie'
    end
    bill.units = 'szt.'
    bill.clearing_id = clearing.id
    bill.user_id = current_user.id
    bill.company_id = company.id

    bill.save ? bill : nil
  end

  def prepare_date(date, sufix = '20')
    str = String.new date
    #FIXME: pamiętać, że dla innego kraju niż IE jest inaczej!
    #Date.strptime(str.insert(-3, sufix), '%d-%m-%Y')
    Date.strptime(str, '%d-%m-%Y')
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/administration.html.erb
<% content_for :section_header do %>
    Administracja
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to 'Administracja', {controller: 'home', action: 'administration'} %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Tutaj znajdują się listy pomocnicze w administracji systemem' %>
<% end %>

<h3>Kraje</h3>
<p><%= link_to 'Dodaj nowy kraj', new_country_path %></p>
<%= render 'countries/countries_table' %>

<h3>Firmy</h3>
<p><%= link_to 'Dodaj nową firmę', new_company_path %></p>
<%= render 'companies/companies_table' %>

<h3>Dokumenty</h3>
<p><%= link_to 'Dodaj nowy dokument', new_document_path %></p>
<%= render 'documents/documents_table' %>

<h3>Lista agentów</h3>
<p><%= link_to 'Dodaj nowego agenta', new_agent_path %></p>
<%= render 'agents/agents_table' %>

<h3>Wgraj plik bazy(UWAGA!!!)</h3>
<%= form_for :file_upload, :url => {controller: 'home', action: 'file_upload'}, :html => {:multipart => true} do |f| %>
    <%= f.file_field :my_file %>
    <%= f.submit "Wgraj", name: nil %>
<% end %>
<br/><br/><br/><br/>

app/views/home/bills_report.html.erb
<% content_for :section_header do %>
    Raport rachunków w danym okresie
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to 'Raporty', home_reports_path %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'W tej sekcji możliwe jest wygenerowanie raportów w możliwych formatach' %>
<% end %>

<h3>Raport rachunków w danym okresie</h3>

<%= search_form_for(@search, url: home_bills_report_path) do |f| %>
    <fieldset>
      <legend>Rachunek</legend>
      <ul>
        <li>
          <%= f.label :issue_date_gteq, 'Data wystawienia od' %>
          <%= f.datepicker :issue_date_gteq %>
        </li>
        <li>
          <%= f.label :issue_date_lteq, 'Data wystawienia do' %>
          <%= f.datepicker :issue_date_lteq %>
        </li>
        <li>
          <%= f.label :number_gteq, 'Numer rachunku od' %>
          <%= f.text_field :number_gteq %>
        </li>
        <li>
          <%= f.label :number_lteq, 'Numer rachunku do' %>
          <%= f.text_field :number_lteq %>
        </li>
        <li>
          <%= f.label :company_id_eq, 'Firma wystawiająca' %>
          <%= f.collection_select :company_id_eq, Company.all_cached, :id, :name, include_blank: "Wszystkie" %>
        </li>
      </ul>
    </fieldset>
    <br/><br/>
    <%= f.submit 'Generuj raport w formacie  html', name: nil %>
    <%= f.submit 'Generuj raport w formacie pdf' %>
    <%= f.submit 'Generuj raport w formacie csv' %>
<% end %>
<% unless @no_html %>
    <br/>
    <h3>Wyniki raportu rachunków w danym okresie</h3>
    <%= render partial: 'bills/bills_table', locals: {bills: @bills} %>
<% end %>

app/views/home/clearings_report.html.erb
<% content_for :section_header do %>
    Raport rozliczeń wg agentów
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to 'Raporty', home_reports_path %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'W tej sekcji możliwe jest wygenerowanie raportów w możliwych formatach' %>
<% end %>

<h3>Raport rozliczeń wg agentów</h3>

<%= search_form_for(@search, url: home_clearings_report_path) do |f| %>
    <fieldset>
      <legend>Rozliczenie</legend>
      <ul>
        <li>
          <%= f.label :year_eq, 'Rok rozliczenia' %>
          <%= f.text_field :year_eq %>
        </li>
        <li>
          <%= f.label :office_send_date_gteq, 'Data wysłania do urzędu ' %>
          <%= f.datepicker :office_send_date_gteq %>
        </li>
        <li>
          <%= f.label :office_send_date_lteq, 'Data wysłania do urzędu' %>
          <%= f.datepicker :office_send_date_lteq %>
        </li>
        <li>
          <%= f.label :country_id_eq, 'Nazwa kraju' %>
          <%= f.collection_select :country_id_eq, Country.all_cached, :id, :name, include_blank: "Wszystkie" %>
        </li>
        <li>
          <%= f.label :payment_date_blank, 'Data zapłaty jest pusta' %>
          <%= f.check_box :payment_date_blank %>
        </li>
      </ul>
    </fieldset>

    <fieldset>
      <legend>Agent</legend>
      <ul>
        <li>
          <%= f.label :agent_id_eq, 'Nazwa agenta' %>
          <%= f.collection_select :agent_id_eq, Agent.all_cached, :id, :name, include_blank: "Wszyscy" %>
        </li>
        <li>
          <%= f.label :agent_date_gteq, 'Data rozliczenia z agentem od' %>
          <%= f.datepicker :agent_date_gteq %>
        </li>
        <li>
          <%= f.label :agent_date_lteq, 'Data rozliczenia z agentem do' %>
          <%= f.datepicker :agent_date_lteq %>
        </li>
        <li>
          <%= f.label :agent_date_blank, 'Data rozliczenia z agentem jest pusta' %>
          <%= f.check_box :agent_date_blank %>
        </li>
      </ul>
    </fieldset>

    <%= f.submit 'Generuj raport w formacie html', name: nil %>
    <%= f.submit 'Generuj raport w formacie pdf' %>
    <%= f.submit 'Generuj raport w formacie csv' %>
<% end %>

<% unless @no_html %>
    <br/>
    <h3>Wyniki raportu rozliczeń wg agentów</h3>
    <%= render partial: 'clearings/clearings_table', locals: {clearings: @clearings} %>
<% end %>

app/views/home/countries_report.html.erb
<% content_for :section_header do %>
    Raport rozliczeń w danym roku dla poszczególnych krajów
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to 'Raporty', home_reports_path %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'W tej sekcji możliwe jest wygenerowanie raportów w możliwych formatach' %>
<% end %>

<h3>Raport rozliczeń w danym roku dla poszczególnych krajów</h3>

<%= search_form_for(@search, url: home_countries_report_path) do |f| %>
    <fieldset>
      <legend>Rozliczenie</legend>
      <ul>
        <li>
          <%= f.label :year_eq, 'Rok rozliczenia' %>
          <%= f.text_field :year_eq %>
        </li>
      </ul>
    </fieldset>

    <fieldset>
      <legend>Kraj</legend>
      <ul>
        <li>
          <%= f.label :country_id_eq, 'Nazwa kraju' %>
          <%= f.collection_select :country_id_eq, Country.all_cached, :id, :name, include_blank: "Wszystkie" %>
        </li>
      </ul>
    </fieldset>

    <%= f.submit 'Generuj raport w formacie html', name: nil %>
    <%= f.submit 'Generuj raport w formacie pdf' %>
    <%= f.submit 'Generuj raport w formacie csv' %>
<% end %>

<% unless @no_html %>
    <br/>
    <h3>Wyniki raportu rozliczeń w danym roku dla poszczególnych krajów</h3>
    <%= render partial: 'clearings/clearings_table', locals: {clearings: @clearings} %>
<% end %>

app/views/home/envelope.html.erb
<% content_for :section_header do %>
    Wydruk koperty
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'W tej sekcji możliwe jest wygenerowanie pliku do wydruku koperty' %>
<% end %>

<h3>Wybierz firmę wystawiającą kopertę</h3>

<%= form_for(:search, url: home_envelope_path, method: :get) do |f| %>
    <fieldset>
      <legend>Koperta</legend>
      <ul>
        <li>
          <%= f.label :client_id, 'Klient' %>
          <%= f.collection_select :client_id, Client.all_cached, :id, :fullname, {selected: @client.id} %>
        </li>
        <li>
          <%= f.label :company_id, 'Firma wystawiająca' %>
          <%= f.collection_select :company_id, Company.all_cached, :id, :name, {selected: @current_user.company.id} %>
        </li>
      </ul>
    </fieldset>
    <br/><br/>
    <%= f.submit 'Generuj kopertę', name: nil %>
<% end %>

app/views/home/file_upload.html.erb
<% content_for :section_header do %>
    Wgrywanie pliku bazy danych
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Na tej stronie znajdują się wyniki wgrywania pliku.' %>
<% end %>

<p><%= "Ilość pobranych linii: #{@tab.size}" %></p>
<p><%= "Ilość błędów: #{@errors.size}" %></p>

<h3>Klienci</h3>
<p><%= "Ilość wgranych klientów: #{@clients.size}" %></p>
<%= content_tag :div, class: 'table' do %>
    <table class="listing jquery_datatable" cellpadding="0" cellspacing="0">
      <thead>
      <%= content_tag :tr do %>
          <%= content_tag :th, 'Identyfikator' %>
          <%= content_tag :th, 'Nazwisko' %>
          <%= content_tag :th, 'Imię' %>
          <%= content_tag :th, 'Miasto' %>
          <%= content_tag :th, 'Telefon kom' %>
          <%= content_tag :th, 'E-mail' %>
          <%= content_tag :th, 'Akcje' %>
      <% end %>
      </thead>
      <tbody>
      <%= content_tag_for(:tr, @clients) do |client| %>
          <%= content_tag :td, (link_to client.identifier, client_path(client)), class: 'style1' %>
          <%= content_tag :td, (link_to client.lastname, client_path(client)), class: 'style1' %>
          <%= content_tag :td, check_blank_value(client.firstname) %>
          <%= content_tag :td, check_blank_value(client.address.city) %>
          <%= content_tag :td, check_blank_value(client.mobile) %>
          <%= content_tag :td, check_blank_value(client.email) %>
          <%= content_tag :td, class: 'actions' do %>
              <%= link_to image_tag('info.png'), client, title: "Szczegółowe informacje" %>
              <%= link_to image_tag('modify.png'), edit_client_path(client), title: "Edycja" %>
              <%= link_to image_tag('delete.png'), client, :confirm => "Czy jesteś pewien?", :method => :delete, title: "Usuwanie" %>
          <% end %>
      <% end %>
      </tbody>
    </table>
<% end %>
<% unless @clients_rep.empty? %>
    <p>Powtórzenia klientów:</p>
    <ul>
      <% @clients_rep.each do |client| %>
          <li><%= client.inspect %></li>
      <% end %>
    </ul>
<% end %>

<h3>Rozliczenia</h3>
<p><%= "Ilość wgranych rozliczeń: #{@clearings.size}" %></p>
<p><%= render partial: 'clearings/clearings_table', locals: {clearings: @clearings} %></p>
<% unless @clearings_rep.empty? %>
    <p>Powtórzenia rozliczeń:</p>
    <ul>
      <% @clearings_rep.each do |clearing| %>
          <li><%= clearing.inspect %></li>
      <% end %>
    </ul>
<% end %>

<h3>Rachunki</h3>
<p><%= "Ilość wgranych rachunków: #{@bills.size}" %></p>
<p><%= render partial: 'bills/bills_table', locals: {bills: @bills} %></p>
<% unless @bills_rep.empty? %>
    <p>Powtórzenia rachunków:</p>
    <ul>
      <% @bills_rep.each do |bills| %>
          <li><%= bills.inspect %></li>
      <% end %>
    </ul>
<% end %>

<% unless @errors.empty? %>
    <h3>Błędy</h3>
    <ul>
      <% @errors.each_with_index do |error, index| %>
          <li><b><%= index+1 %></b><%= error.inspect %></li>
      <% end %>
    </ul>
<% end %>

app/views/home/index.html.erb
<% content_for :section_header do %>
    Rozliczenia w toku
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Tutaj znajduje się strona główna aplikacji. Szczegóły do uzgodnienia.' %>
<% end %>

<%= content_tag :div, class: 'table' do %>
    <table id="home_clearings_table" class="listing jquery_datatable" cellpadding="0" cellspacing="0">
      <thead>
      <%= content_tag :tr do %>
          <%= content_tag :th, 'Nazwisko' %>
          <%= content_tag :th, 'Imię' %>
          <%= content_tag :th, 'Kraj' %>
          <%= content_tag :th, 'Rok' %>
          <%= content_tag :th, 'Numer podatkowy' %>
          <%= content_tag :th, 'Wyliczony zwrot' %>
          <%= content_tag :th, 'Data wysłania do urzędu' %>
          <%= content_tag :th, 'Akcje' %>
      <% end %>
      </thead>
      <tbody>
      <%= content_tag_for(:tr, @clearings) do |clearing| %>
          <%= content_tag :td, ((link_to clearing.client.lastname, client_path(clearing.client)) unless clearing.client.nil?), class: 'style1' %>
          <%= content_tag :td, ((link_to clearing.client.firstname, client_path(clearing.client)) unless clearing.client.nil?), class: 'style1' %>
          <%= content_tag :td, ((link_to clearing.country.short, country_path(clearing.country)) unless clearing.country.nil?), class: 'style1' %>
          <%= content_tag :td, clearing.year.nil? ? "Brak" : link_to(clearing.year, clearing), class: 'style1' %>
          <%= content_tag :td, (clearing.tax_number.empty? ? "Brak" : link_to(clearing.tax_number, clearing)), class: 'style1' %>
          <%= content_tag :td, clearing.rebate_calc.nil? ? "Brak" : number_to_currency(clearing.rebate_calc) %>
          <%= content_tag :td, clearing.office_send_date.nil? ? "Brak" : l(clearing.office_send_date) %>
          <%= content_tag :td, class: 'actions' do %>
            <%= link_to image_tag('info.png'), clearing, title: "Szczegółowe informacje" %>
            <%= link_to image_tag('modify.png'), edit_clearing_path(clearing), title: "Edycja rozliczenia" %>
            <% if clearing.bill.nil? %>
              <%= link_to image_tag('invoice.png'), new_clearing_bill_path(clearing), title: "Nowy rachunek" %>
            <% else %>
              <%= link_to image_tag('invoice.png'), edit_bill_path(clearing.bill), title: "Edycja rachunku" %>
            <% end %>
            <%= link_to image_tag('message.png'), new_clearing_message_path(clearing), title: "Nowa wiadomość do rozliczenia" %>
            <%= link_to image_tag('delete.png'), clearing, :confirm => "Czy jesteś pewien?", :method => :delete, title: "Usuwanie" %>
          <% end %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/home/reports.html.erb
<% content_for :section_header do %>
    Raporty
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to 'Raporty', {controller: 'home', action: 'reports'} %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'W tej sekcji możliwe jest wygenerowanie raportów w możliwych formatach' %>
<% end %>

<h3>Raport rozliczeń</h3>
<p><%= button_to 'Idź do raportu', home_clearings_report_path, method: :get %></p>


<h3>Raport rachunków</h3>
<p><%= button_to 'Idź do raportu', home_bills_report_path, method: :get %></p>

<!--
<h3>Raport rozliczeń w danym roku dla poszczególnych krajów</h3>
<p><%# button_to 'Idź do raportu', home_countries_report_path, method: :get %></p>
-->