config/routes.rb
Europodatki::Application.routes.draw do
  resources :enclosures

  resources :agents

  resources :bills

  resources :clearings do
    member do
      get 'history'
    end
    resource :bill, only: [:new]
    resources :messages, only: [:new, :index]
    resources :enclosures, only: [:new, :index]
  end

  resources :companies

  resources :documents

  resources :countries do
    resources :documents, only: [:new, :index]
  end

  resources :messages

  resources :clients do
    member do
      get 'history'
    end
    collection do
      get 'autocomplete_client_lastname'
    end
    resources :clearings, only: [:new, :index]
  end

  devise_for :users
  resources :users, :only => [:show, :index]

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  root :to => 'home#index'

  match 'home/administration' => 'home#administration', :as => 'home_administration'
  match 'home/reports' => 'home#reports', :as => 'home_reports'
  match 'home/bills_report' => 'home#bills_report', :as => 'home_bills_report'
  match 'home/clearings_report' => 'home#clearings_report', :as => 'home_clearings_report'
  #match 'home/countries_report' => 'home#countries_report', :as => 'home_countries_report'
  match 'home/file_upload' => 'home#file_upload', :as => 'home_file_upload'
  match 'home/envelope' => 'home#envelope', :as => 'home_envelope'
end

app/models/bill.rb
#encoding: utf-8
require 'prawn'
#require 'numbers_and_words'

class Bill < ActiveRecord::Base
  belongs_to :clearing
  belongs_to :company
  belongs_to :user

  delegate :client, to: :clearing, allow_nil: true

  attr_accessible :clearing_id, :company_id, :total, :maturity_date, :issue_date, :comment, :user_id, :payment_form, :title, :units, :number, :total_manual, :number_manual, :currency

  validates_presence_of :clearing_id, :company_id, :user_id, :total, :issue_date, :maturity_date, :currency

  def self.all_cached
    Rails.cache.fetch('Bill.all') { Bill.includes([:company, {:clearing => [:client, :country]}]).order('number') }
  end

  after_save :expire_all_cache
  before_validation :set_number
  after_create :set_number_in_company
  after_destroy :expire_all_cache

  def expire_all_cache
    Rails.cache.delete('Bill.all')
  end

  def to_pdf
    pdf = Prawn::Document.new(:page_size => "A4")
    pdf.font_families.update("mine" => {
        :bold => "#{Rails.root}/app/assets/fonts/DejaVuSans-Bold.ttf",
        :italic => "#{Prawn::BASEDIR}/data/fonts/DejaVuSans.ttf",
        :bold_italic => "#{Prawn::BASEDIR}/data/fonts/DejaVuSans.ttf",
        :normal => "#{Prawn::BASEDIR}/data/fonts/DejaVuSans.ttf"})
    pdf.font("mine")

    prepare_pdf pdf, "Oryginał"

    pdf.start_new_page

    prepare_pdf pdf, "Kopia"

    file = File.join(Rails.root, "tmp", "rachunek.pdf")
    pdf.render_file file

    file
  end

  private
  def prepare_pdf(pdf, original)
    pdf.font_size 9

    pdf.move_down 15

    pdf.text "#{self.company.address.city}, #{self.issue_date}", align: :right

    pdf.move_down 25

    pdf.font_size 12

    pdf.text "Rachunek nr: #{self.number}", style: :bold, align: :center
    pdf.text original, align: :center

    pdf.font_size 9

    pdf.move_down 25

    table_left = pdf.make_table([["#{self.company.name}"], [""], ["#{self.company.address.street}"], ["#{self.company.address.code} #{self.company.address.city}"], ["NIP #{self.company.tax_number}"]], width: 260, :cell_style => {:borders => [], align: :center})
    table_right = pdf.make_table([["#{self.clearing.client.fullname}"], [""], ["#{self.clearing.client.address.street}"], ["#{self.clearing.client.address.code} #{self.clearing.client.address.city}"]], width: 260, :cell_style => {:borders => [], align: :center})
    cell_header_left = pdf.make_cell(content: "<b>Sprzedawca</b>", inline_format: true, align: :center)
    cell_header_right = pdf.make_cell(content: "<b>Nabywca</b>", inline_format: true, align: :center)
    table_data = [[cell_header_left, cell_header_right], [table_left, table_right]]
    pdf.table(table_data, header: true, width: 520, position: :center)

    pdf.move_down 25

    table_left = pdf.make_table([["Data sprzedaży: #{helpers.localize(self.issue_date)}"], ["Termin zapłaty: #{helpers.localize(self.maturity_date)}"], ["Sposób zapłaty: #{self.payment_form}"]], width: 260, :cell_style => {:borders => [], align: :left})

    if self.payment_form.eql? 'Przelew'
      table_right = pdf.make_table([["Bank: #{self.company.bank_name}"], ["Numer konta: #{self.company.account_number}"], [""]], width: 260, :cell_style => {:borders => [], align: :left})
    else
      table_right = pdf.make_table([[""], [""], [""]], width: 260, :cell_style => {:borders => [], align: :left})
    end

    pdf.table([[table_left, table_right]], width: 520, position: :center, :cell_style => {:borders => []})

    pdf.move_down 25

    table_data = [[pdf.make_cell(content: "<b>Lp.</b>", inline_format: true), pdf.make_cell(content: "<b>Nazwa towaru / usługi</b>", inline_format: true), pdf.make_cell(content: "<b>Ilość</b>", inline_format: true), pdf.make_cell(content: "<b>Jedn. miary</b>", inline_format: true), pdf.make_cell(content: "<b>Cena jednostki</b>", inline_format: true), pdf.make_cell(content: "<b>Wartość</b>", inline_format: true)],
                  [pdf.make_cell(content: "1"), pdf.make_cell(content: "#{self.title}"), pdf.make_cell(content: "1"), pdf.make_cell(content: "#{self.units}"), pdf.make_cell(content: "#{helpers.number_with_precision(self.total, precision: 2, delimiter: " ")}"), pdf.make_cell(content: "#{helpers.number_with_precision(self.total, precision: 2, delimiter: " ")}")]]
    pdf.table(table_data, header: true, width: 520, position: :center)

    pdf.move_down 25

    if self.comment && !self.comment.empty?
      pdf.text "Adnotacje:", style: :bold_italic, align: :left
      pdf.text "#{self.comment}", style: :italic, align: :left
    end

    pdf.move_down 45

    pdf.text "Do zapłaty: #{helpers.number_with_precision(self.total, precision: 2, delimiter: " ")} #{self.currency}", style: :bold

    pdf.move_down 25

    pdf.text "Słownie: #{price_to_words(helpers.number_with_precision(self.total, precision: 2, delimiter: " "), self.currency)}"

    pdf.move_down 90

    pdf.table([[pdf.make_cell(content: "podpis odbiorcy", align: :center, :borders => []), pdf.make_cell(content: "podpis wystawcy", align: :center, :borders => [])]], header: true, width: 520, position: :center)
  end

  def helpers
    ActionController::Base.helpers
  end

  def set_number
    self.number = "#{self.company.bill_number.to_i + 1}/#{Date.current.year}" if self.number.blank?
    self.number = self.number.insert(0, '0') if self.number.to_s.size < 7
    self.number = self.number.insert(0, '0') if self.number.to_s.size < 8
  end

  def set_number_in_company
    unless self.number_manual
      self.company.update_attribute :bill_number, (self.company.bill_number.to_i + 1)
    end
  end

  def price_to_words(price, currency)
    hash = %w(zer jed dwa trz czt pię sze sie osi dzi)
    str = ""
    grosze = false
    price.to_s.each_char do |s|
      if s.eql? ","
        grosze = true
        str += "zł*" if currency.eql? 'PLN'
        str += "EURO*" if currency.eql? 'EURO'
      else
        if grosze
          str += "#{s}"
        else
          str += "#{hash[s.to_i]}*"
        end
      end
    end
    str += "/100"
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  before_filter :authenticate_user!

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all_cached

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
      format.pdf do
        send_file @bill.to_pdf, :filename => "rachunek_#{l Date.current}.pdf", :type => "application/pdf"
      end
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    create_company_cookies
    if params[:clearing_id]
      @clearing = Clearing.find(params[:clearing_id])
      @bill = @clearing.build_bill
      @bill.total = @clearing.commission_final unless @clearing.commission_final.nil?
    else
      @bill = Bill.new
    end
    @bill.issue_date = Date.today

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    create_company_cookies
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(check_number_with_comma(params[:bill]))
    @bill.user_id = current_user.id

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: t('flash.notice') }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(check_number_with_comma(params[:bill]))
        format.html { redirect_to @bill, notice: t('flash.notice') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url, notice: t('flash.notice') if @bill.destroyed? }
      format.json { head :no_content }
    end
  end

  private
  def create_company_cookies
    Company.all_cached.each do |company|
      cookies[company.id] = "#{company.bill_number.to_i + 1}/#{Date.current.year}"
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bills_table.html.erb
<%= content_tag :div, class: 'table' do %>
    <table class="listing jquery_datatable" cellpadding="0" cellspacing="0">
      <thead>
      <%= content_tag :tr do %>
          <%= content_tag :th, 'Numer' %>
          <%= content_tag :th, 'Firma' %>
          <%= content_tag :th, 'Rozliczenie' %>
          <%= content_tag :th, 'Data wystawienia' %>
          <%= content_tag :th, 'Termin płatności' %>
          <%= content_tag :th, 'Akcje' %>
      <% end %>
      </thead>
      <tbody>
      <%= content_tag_for(:tr, bills) do |bill| %>
          <%= content_tag :td, (link_to(bill.number, bill) unless bill.number.nil?), class: 'style1' %>
          <%= content_tag :td, (link_to(bill.company.name, company_path(bill.company)) unless bill.company.nil?), class: 'style1' %>
          <%= content_tag :td, (link_to(bill.clearing.title, clearing_path(bill.clearing)) unless bill.clearing.nil?), class: 'style1' %>
          <%= content_tag :td, check_blank_value(bill.issue_date) %>
          <%= content_tag :td, check_blank_value(bill.maturity_date) %>
          <%= content_tag :td, class: 'actions' do %>
              <%= link_to image_tag('info.png'), bill, title: "Szczegółowe informacje" %>
              <%= link_to image_tag('modify.png'), edit_bill_path(bill) %>
              <%= link_to image_tag('delete.png'), bill, :confirm => "Czy jesteś pewien?", :method => :delete %>
          <% end %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
    <% if @bill.errors.any? %>
        <div id="error_explanation">
          <h2><%= "Wykrytych błędów: #{@bill.errors.count}" %></h2>

          <ul>
            <% @bill.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="table">
      <table class="listing form" cellpadding="0" cellspacing="0">
        <tr>
          <th class="full" colspan="2">Formularz nowego rachunku</th>
        </tr>
        <tr>
          <td><strong><%= f.label :number_manual, "Numer rachunku wpisany ręcznie" %></strong></td>
          <td>
            <%= f.check_box :number_manual %>
          </td>
        </tr>
        <tr>
          <td><strong><%= f.label :number, "Numer rachunku" %></strong></td>
          <td>
            <% if @bill.new_record? %>
                <%= f.text_field :number, value: "#{Company.all_cached.first.bill_number.to_i + 1}/#{Date.current.year}", readonly: true %>
            <% else %>
                <% if @bill.number_manual? %>
                    <%= f.text_field :number %>
                <% else %>
                    <%= f.text_field :number, readonly: true %>
                <% end %>
            <% end %>
          </td>
        </tr>
        <% if @bill.new_record? %>
            <tr>
              <td><strong><%= f.label :clearing_id, "Rozliczenie powiązane z rachunkiem" %></strong></td>
              <td>
                <%= f.collection_select :clearing_id, Clearing.without_bill, :id, :title, {prompt: true}, {'data-message' => Clearing.generate_final_commissions} %>
              </td>
            </tr>
        <% else %>
            <tr>
              <td><strong><%= f.label :clearing_id, "Rozliczenie powiązane z rachunkiem" %></strong></td>
              <td>
                <%= f.collection_select :clearing_id, [@bill.clearing], :id, :title, {prompt: true}, {'data-message' => Clearing.generate_final_commissions} %>
              </td>
            </tr>
        <% end %>

        <tr>
          <td><strong><%= f.label :company_id, "Firma wystawiająca" %></strong></td>
          <td>

            <%= f.collection_select :company_id, Company.all_cached, :id, :name
            %>
          </td>
        </tr>
        <tr>
          <td><strong><%= f.label :issue_date, "Data wystawienia rachunku" %></strong></td>
          <td>
            <%= f.datepicker :issue_date, class: 'datepicker' %>
          </td>
        </tr>
        <tr>
          <td><strong><%= f.label :maturity_date, "Termin płatności" %></strong></td>
          <td>
            <%= f.datepicker :maturity_date, class: 'datepicker' %>
          </td>
        </tr>

        <tr>
          <td><strong><%= f.label :payment_form, "Forma płatności" %></strong></td>
          <td>
            <%= f.select :payment_form, options_for_select(%w(Pobranie Gotówka Przelew), @bill.payment_form) %>
          </td>
        </tr>
        <tr>
          <td><strong><%= f.label :title, "Tytuł usługi" %></strong></td>
          <td>
            <%= f.select :title, options_for_select(['Usługa inkasa', 'Usługa biurowa'], @bill.title) %>
          </td>
        </tr>
        <tr>
          <td><strong><%= f.label :units, "Jednostka miary" %></strong></td>
          <td>
            <%= f.text_field :units, value: @bill.units.blank? ? "szt." : @bill.units %>
          </td>
        </tr>
        <tr>
          <td><strong><%= f.label :total_manual, "Kwota końcowa wpisana ręcznie" %></strong></td>
          <td>
            <%= f.check_box :total_manual %>
          </td>
        </tr>
        <tr>
          <td><strong><%= f.label :total, "Kwota końcowa" %></strong></td>
          <td>
            <% if @bill.total_manual? %>
                <%= f.decimal_field :total %>
            <% else %>
                <%= f.decimal_field :total, readonly: true %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><strong><%= f.label :currency, "Waluta" %></strong></td>
          <td>
            <%= f.select :currency, options_for_select(['PLN', 'EURO', 'FUNT'], @bill.currency) %>
          </td>
        </tr>
        <tr>
          <td><strong><%= f.label :comment, "Dodatkowe informacje" %></strong></td>
          <td>
            <%= f.text_area :comment, :rows => 2 %>
          </td>
        </tr>
        <tr>
          <td class="full" colspan="2"><%= f.submit "Zapisz" %></td>
        </tr>
      </table>
    </div>
<% end %>

app/views/bills/_main_menu.html.erb
<% if @bill && !@bill.new_record? %>
    <h3><%= @bill.number %></h3>
    <ul class="nav">
      <li><%= link_to 'Szczegóły', @bill %></li>
      <li><%= link_to 'Edycja', edit_bill_path(@bill) %></li>
      <li><%= link_to 'Wydrukuj', bill_path(@bill, format: :pdf) %></li>
      <li><%= link_to 'Usuń', @bill, :confirm => "Czy jesteś pewien?", :method => :delete %></li>
      <li><%= link_to 'Do klienta', @bill.client %></li>
      <li><%= link_to 'Do rozliczenia', @bill.clearing %></li>
    </ul>
<% end %>
<h3>Rachunki</h3>
<ul class="nav">
  <li><%= link_to 'Nowy rachunek', new_bill_path %></li>
  <li><%= link_to 'Lista rachunków', bills_path %></li>
  <li></li>
</ul>

app/views/bills/edit.html.erb
<% content_for :section_header do %>
    Edycja rachunku
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Edycja rachunku", edit_bill_path(@bill) %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'W tym miejscu aplikacji możliwa jest edycja danych rachunku.' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<%= render 'form' %>

app/views/bills/index.html.erb
<% content_for :section_header do %>
    Lista wystawionych rachunków
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Lista rachunków", bills_path %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Lista wszystkich rekordów rachunków z bazy danych' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<%= content_tag :div, class: 'table' do %>
    <table class="listing jquery_datatable" cellpadding="0" cellspacing="0">
      <thead>
      <%= content_tag :tr do %>
          <%= content_tag :th, 'Numer' %>
          <%= content_tag :th, 'Firma' %>
          <%= content_tag :th, 'Rozliczenie' %>
          <%= content_tag :th, 'Data wystawienia' %>
          <%= content_tag :th, 'Termin płatności' %>
          <%= content_tag :th, 'Akcje' %>
      <% end %>
      </thead>
      <tbody>
      <%= content_tag_for(:tr, @bills) do |bill| %>
          <%= content_tag :td, (link_to(bill.number, bill) unless bill.number.nil?), class: 'style1' %>
          <%= content_tag :td, (link_to(bill.company.name, company_path(bill.company)) unless bill.company.nil?), class: 'style1' %>
          <%= content_tag :td, (link_to(bill.clearing.title, clearing_path(bill.clearing)) unless bill.clearing.nil?), class: 'style1' %>
          <%= content_tag :td, check_blank_value(bill.issue_date) %>
          <%= content_tag :td, check_blank_value(bill.maturity_date) %>
          <%= content_tag :td, class: 'actions' do %>
              <%= link_to image_tag('info.png'), bill, title: "Szczegółowe informacje" %>
              <%= link_to image_tag('modify.png'), edit_bill_path(bill), title: "Edycja" %>
              <%= link_to image_tag('print.png'), bill_path(bill, format: :pdf), title: "Drukuj" %>
              <%= link_to image_tag('delete.png'), bill, :confirm => "Czy jesteś pewien?", :method => :delete, title: "Usuwanie" %>
          <% end %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/bills/new.html.erb
<% content_for :section_header do %>
    Dodawanie nowego rachunku
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Dodawanie rachunku", new_clearing_path %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Dodawanie nowego rekordu rachunku' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<%= render 'form' %>

app/views/bills/show.html.erb
<% content_for :section_header do %>
    Szczegóły rachunku
<% end %>

<% content_for :history do %>
    <%= link_to "Rozliczenia w toku", root_url %> / <%= link_to "Szczegóły rachunku", bill_path(@bill) %> / <%= link_to 'Wstecz', :back %>
<% end %>

<% content_for :help do %>
    <% help_block 'Podgląd danych wystawionego rachunku' %>
<% end %>

<% content_for :main_menu do %>
    <% render 'main_menu' %>
<% end %>

<div class="table">
  <table class="listing form" cellpadding="0" cellspacing="0">
    <tr>
      <th class="full" colspan="2">Szczegóły rekordu rachunku</th>
    </tr>
    <%= check_blank 'Rozliczenie', @bill.clearing.title %>
    <%= check_blank 'Numer', @bill.number %>
    <%= check_blank 'Firma', @bill.company.name %>
    <%= check_blank('Data wystawienia', check_blank_value(@bill.issue_date)) %>
    <%= check_blank('Termin płatności', check_blank_value(@bill.maturity_date)) %>
    <%= check_blank('Kwota końcowa', number_with_precision(@bill.total, precision: 2, delimiter: " ")) %>
    <%= check_blank 'Waluta', @bill.currency %>
    <%= check_blank 'Forma płatności', @bill.payment_form %>
    <%= check_blank 'Tytuł usługi', @bill.title %>
    <%= check_blank 'Jednostka miary', @bill.units %>
    <%= check_blank 'Użytkownik wystawiający', @bill.user.name %>
    <tr>
      <th class="full" colspan="2">Dodatkowe informacje</th>
    </tr>
    <tr>
      <td colspan="2"><%= @bill.comment.blank? ? "Brak" : @bill.comment %></td>
    </tr>
  </table>
</div>